### ISSUE TITLE
Launch server

### ISSUE THREAD

**Issue by kosssi** [whisller/IrcBotBundle#10]
How can i launch a server without load configuration ?

For exemple :

launchServer($server, $port, $channels)

It's possible ?

**Comment by phillpafford** [comment]
Could you explain a little more? Example?

**Comment by whisller** [comment]
But IrcBotBundle is not an IRC server, or even a irc client. IrcBotBundle is simulating the user, that is logging into irc server and joining the channel, and listening on specified messages.

If you want to run IrcBotBundle you will need have Symfony2 configuration because in it is defined required configuration that is used for bundle.

**Comment by kosssi** [comment]
yes i know. Sorry for my english, i speak very bad.

you can see my ManagerIrcBot bundle in github. https://github.com/kosssi/ManagerIrcBot

It's for create, edit and delete servers for to connect to multiple channels.
the last party is a client's launch. And I block here.

I saved the pid in a database, so i can verificate if it is launched or not, i can kill it... but i don't know how launch the client irc properly...

You can help me ?

**Comment by whisller** [comment]
IrcBotBundle has an option to join many channels on one Irc server. If you want to connect it to many servers you need to run different instances of bundle.
